knpu_oauth2_client:
    clients:
        github:
            type: github
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: auth_oauth_check
            redirect_params: { service: google }  # MUST match the client key above

            # whether to check OAuth2 "state": defaults to true
            # use_state: true
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: auth_oauth_check
            redirect_params: { service: google }  # MUST match the client key above
